SELECT NAME AS 'CUSTOMER', 
CONCAT(STATE,', ', CITY) AS 'STATE/CITY', 
CREDITLIMIT 
FROM CUSTOMER
WHERE NAME = 'MERCURY LTD' OR NAME = 'VENUS LLC' OR NAME = 'MARS INC'
--WHERE NOT (CREDITLIMIT >= 250000 AND CREDITLIMIT <= 500000
--AND STATE = 'KY')
--WHERE STATE = 'OH' OR STATE = 'IN'