SELECT * FROM CARS
INSERT CARS
   (MAKE, MODEL, [TRIM], [YEAR], ISsEDAN, PURCHASEPRICE)
   VALUES
   ('DODGE', 'CHALLENGER', 'RT', 2012, 0, 18000)


INSERT CARS
      (MAKE, MODEL, [TRIM], [YEAR], ISsEDAN, PURCHASEPRICE)
	  VALUES
	  ('CHRYSLER', 300, 'NO', 2007, 1, 8000)